apiVersion: apps/v1
kind: Deployment
metadata:
  name: tothemoon-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tothemoon-user
  template:
    metadata:
      labels:
        app: tothemoon-user
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: tothemoon-user
        image: siavashnezhad/tothemoon-user:${{github.run_number}}
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: tothemoon-user
spec:
  ports:
  - port: 80
  selector:
    app: tothemoon-user
